### ISSUE TITLE
When hassession response is resolved from cache, the event are not emitted

### ISSUE THREAD

**Issue by userpixel** [schibsted/account-sdk-browser#45] opened 2018-05-24 14:54 UTC
*Bug*

### Steps to reproduce

1. Go to sdk-example
2. Log in
3. Open developer tools > Sources and pick webpack:///./node_modules/@schibsted/account-sdk-browser/src/identity.js
4. Put a breakpoint in line 196 that reads as `if (current.visitor) {`
5. Refresh the page and notice that the event emitting code isn't executed

**Comment by torarvid** [comment] 2018-05-24 15:00
Duplicate of #40

**Closed by torarvid** 2018-05-24 15:00 UTC
